# These are some ways using which you can tip developers of the openx project.

Bitcoin: 1hQ4Vz287UWdyocjH9JTDK5L1tnjctWUY
Bitcoin Cash: 124SUMYLGKe8WjjGXWXvDoYTLKRbvsvPif
Ethereum: 0x7b82e04f18e49e1286db818a15a3d6381291910e
Stellar: address GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3, memo 8272a9eff6f946ac8fb
Dogecoin: DQTSVt62WTXLrVB4UmYkxaHy1DzVg8RT6q

# Thank you for your kind contributions and extended support.
