dist: xenial
notifications:
  email: false
language: go
go:
  - 1.13.x
script:
  - go test --tags="travis" -coverprofile=coverage.txt -covermode=atomic ./...
  - go build -v ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)