dist: xenial
notifications:
  email: false
language: go
go:
  - 1.12.x
script:
  - go test --tags="travis" -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
