dist: xenial
notifications:
  email: false
language: go
go:
  - 1.11.x
before_install:
  - go get github.com/stellar/go
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cd ${TRAVIS_HOME}/gopath/src/github.com/stellar/go
  #- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  #- rm Gopkg.lock
  - dep ensure -v
  - cd ${TRAVIS_HOME}/gopath/src/github.com/YaleOpenLab/openx
  - git clone https://github.com/Varunram/easyjson.git
  - go get -u github.com/mailru/easyjson/...
  - go get github.com/pkg/errors
script:
  - ./easyjson/linux/easyjson -all */*.go
  - ./easyjson/linux/easyjson -all */**/*.go
  - ./easyjson/linux/easyjson -all */**/**/*.go
  - go test --tags="travis" -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
